"""reduce first_name length to 25

Revision ID: 77901342b859
Revises: 36cc8f000424
Create Date: 2025-08-26 20:04:07.837376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77901342b859'
down_revision: Union[str, Sequence[str], None] = '36cc8f000424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=25),
               existing_nullable=False)
    op.alter_column('contacts', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=25),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contacts', 'last_name',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('contacts', 'first_name',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
